# Tahap 1: Build React app
FROM node:18-alpine AS build
WORKDIR /app

# Copy package.json dan install semua dependensi (termasuk dev)
COPY package*.json ./
RUN npm install

# Copy semua source dan build
COPY . .
RUN npm run build

# Tahap 2: Jalankan hasil build dengan Nginx
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
