# Tahap 1: Build React app
FROM node:18-alpine AS build
WORKDIR /app

# Salin file package.json & install dependencies
COPY package*.json ./
RUN npm install

# Salin semua source code dan build
COPY . .
RUN npm run build

# Tahap 2: Serve dengan Nginx
FROM nginx:stable-alpine

# Salin hasil build React
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Jalankan Nginx
CMD ["nginx", "-g", "daemon off;"]
