# Gunakan image Node.js versi stabil
FROM node:18-alpine

# Tentukan working directory
WORKDIR /app

# Salin package.json dan package-lock.json terlebih dahulu
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Salin seluruh source code ke dalam container
COPY . .

# Tentukan port backend (misal dari .env PORT=4000)
EXPOSE 4000

# Jalankan aplikasi
CMD ["npm", "start"]
