# Tahap 1: build React app
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Tahap 2: serve hasil build menggunakan Nginx
FROM nginx:stable-alpine

# Salin hasil build dari tahap sebelumnya
COPY --from=build /app/build /usr/share/nginx/html

# Port default Nginx
EXPOSE 80

# Jalankan Nginx
CMD ["nginx", "-g", "daemon off;"]
